version: '3.1'

services:
  oracle-xe:
    image: container-registry.oracle.com/database/express:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=top_secret
    networks:
      - oracle-net

networks:
  oracle-net:
    driver: bridge
