version: '3.1'

services:
  oracle-xe:
    image: container-registry.oracle.com/database/express:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PDB=XEPDB1
      - ORACLE_PWD=<your-password>
    networks:
      - oracle-net

networks:
  oracle-net:
    driver: bridge
